
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 25 16:12:38 PDT 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Expresiones = 22;
  public static final int Incremento = 70;
  public static final int Excepcion = 28;
  public static final int Seleccionar = 38;
  public static final int Pentur = 59;
  public static final int AbriPar = 61;
  public static final int Coma = 69;
  public static final int Dividido = 75;
  public static final int Salto = 30;
  public static final int Etiqueta = 20;
  public static final int Matematico = 17;
  public static final int Imagen = 40;
  public static final int Tipo = 41;
  public static final int Tamano = 46;
  public static final int Flujo = 49;
  public static final int Importar = 26;
  public static final int Archivo = 52;
  public static final int AbriCor = 63;
  public static final int Memoria = 50;
  public static final int Fun = 68;
  public static final int Resta = 73;
  public static final int Suma = 72;
  public static final int TerminarIns = 36;
  public static final int ERROR = 10;
  public static final int OperadorRelacional = 8;
  public static final int CierraPar = 62;
  public static final int Imprimir = 27;
  public static final int Cadena = 34;
  public static final int Principal = 33;
  public static final int Trigonometria = 15;
  public static final int OtroCasoUlt = 5;
  public static final int Evento = 39;
  public static final int Desde = 77;
  public static final int CierraCor = 64;
  public static final int Caso = 76;
  public static final int Sincronizacion = 54;
  public static final int Mensaje = 55;
  public static final int ComentarioEspecifico = 42;
  public static final int AbriLla = 65;
  public static final int OtroCaso = 6;
  public static final int Elipse = 47;
  public static final int CicloF = 4;
  public static final int Cerrar = 24;
  public static final int CicloD = 3;
  public static final int Evaluar = 2;
  public static final int Clonacion = 45;
  public static final int Rellenar = 60;
  public static final int Concurrencia = 53;
  public static final int EOF = 0;
  public static final int Dirtur = 58;
  public static final int Logico = 11;
  public static final int Desplazamiento = 43;
  public static final int Convertir = 13;
  public static final int Numero = 9;
  public static final int Busqueda = 51;
  public static final int BitAsignacion = 44;
  public static final int Acceso = 16;
  public static final int CierraLla = 66;
  public static final int Literal = 67;
  public static final int error = 1;
  public static final int Pila = 32;
  public static final int Aleatorio = 25;
  public static final int Array = 21;
  public static final int Granuladidad = 56;
  public static final int Optur = 57;
  public static final int Limpia = 19;
  public static final int Leer = 18;
  public static final int Identificador = 7;
  public static final int Conjunto = 48;
  public static final int Por = 74;
  public static final int Agrupacion = 35;
  public static final int Comentario = 12;
  public static final int Alias = 37;
  public static final int Funciones = 14;
  public static final int Longitud = 23;
  public static final int Igual = 71;
  public static final int OpListas = 31;
  public static final int EvaluacionLog = 29;
}

